# -*- coding: utf-8 -*-
"""AUDIO CLASSIFICATION WITH GRADIO INTERFACE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V2w86us7IM2yeLbyy7lyDyJcCf3sbxOz
"""

from transformers import pipeline
import gradio as gr

# Define the model pipeline for audio classification
model_id = "sanchit-gandhi/distilhubert-finetuned-gtzan"
pipe = pipeline("audio-classification", model=model_id)

# Function to classify audio
def classify_audio(filepath):
    preds = pipe(filepath)
    outputs = {}
    for p in preds:
        outputs[p["label"]] = p["score"]
    return outputs

# Gradio interface
demo = gr.Interface(
    fn=classify_audio,
    inputs=gr.Audio(type="filepath"),
    outputs=gr.Label()  # Use gr.Label instead of gr.outputs.Label()
)

# Launch the app
demo.launch(debug=True)